### ISSUE TITLE
Dependency Maintainance 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1529]
According to pur
looking at the requirements specified in setup.py
these are the latest dep version

whether we can update is another issue ...

- ccg-django-utils==0.4.2 <-- this is the current version
- [x] celery==4.4.7 from 4.4.2 (#1535)
- [x] Django==2.2.13 from 2.1.15 (#1526)
- [x] django-ajax-selects==1.9.1 from 1.7.1 (#1536)
- [x] django-anymail==7.2.1 from 7.0.0 (#1533)
- [x] django-countries==6.1.3 from 5.5
- [ ] django-extensions==3.0.0 from 2.2.5
- django-iprestrict==1.7.0 <-- this is the current version
- django-messages-ui==2.0.2 <-- this is the current version
- [x] django-nose==1.4.7 from 1.4.6
- django-positions==0.6.0 <-- this is the current version
- [ ] django-registration-redux==2.8 from 2.6
- djangorestframework==3.9.4 <-- this is the current version
- [ ] django-storages==1.9.1 from 1.8
- django-templatetag-handlebars==1.3.1 <-- this is the current version
- django-templatetag-sugar==1.0 <-- this is the current version
- django-useraudit==1.7.1 <-- this is the current version
- django-uwsgi==0.2.2 <-- this is the current version
- [ ] geoip2==3.0.0 from 2.9.0.
- jsonschema==3.2.0 <-- this is the current version
- openpyxl==2.6.4 <-- this is the current version
- polib==1.1.0 <-- this is the current version
- [ ] psycopg2==2.8.5 from 2.8.4
- [ ] pycountry==20.7.3 from 19.8.18
- pyinotify==0.9.6 <-- this is the current version
- [ ] pyodbc==4.0.30 from 4.0.27
- [ ] pyparsing==2.4.7 from 2.4.5
- python-dateutil==2.8.1 <-- this is the current version
- python-memcached==1.59 <-- this is the current version
- [ ] pyyaml==5.3.1 from 5.2
- [ ] setuptools 
- [ ] setuptools_scm==4.1.2 from 3.3.3
- [ ] six==1.15.0 from 1.13.0
- SQLAlchemy==1.3.19 from 1.3.12 (#1526 - django 2.2.3 causing a stellar issue, SQLAlchemy downgraded to 2.1.5)
- [ ] uwsgi==2.0.19.1 from 2.0.18
- django-formtools==2.2 <-- this is the current version
- [ ] django-otp==1.0.0 from 0.7.4
- django-phonenumber-field==2.4.0  <-- this is the current version
- [x] django-two-factor-auth==1.12.1 from 1.12.0 (#1525)
- [ ] phonenumberslite==8.12.8 from 8.11.1
- Pillow==6.2.2 <-- this is the current version
- qrcode==6.1 <-- this is the current version
- django-reversion==3.0.5 <-- this is the current version
- [ ] ua-parser==0.10.0 from 0.8.0
- [x] user-agents==2.2.0 from 2.0
- [ ] django-user-agents==0.4.0 from 0.3.2
- [ ] django-simple-history==2.11.0 from 2.8.0
- [ ] python-ldap==3.3.1 (was not pinned)
- [ ] django-auth-ldap==2.2.0 (was not pinned)
- [ ] django-session-security==2.6.6 from 2.6.5
- Markdown==3.1.1 <-- this is the current version
- [ ] xhtml2pdf==0.2.4 (was not pinned)
- django-redis==4.11.0 <-- this is the current version
- [ ] kombu==4.6.11 from 4.6.8

**Comment by id2359** [comment]
On staging the actual packages currently installed in the container are:

Babel==2.8.0
Django==2.1.15
Markdown==3.1.1
Pillow==6.2.2
PyPDF2==1.26.0
PyYAML==5.2
SQLAlchemy==1.3.12
amqp==2.5.2
attrs==20.1.0
billiard==3.6.3.0
ccg-django-utils==0.4.2
celery==4.4.2
certifi==2020.6.20
chardet==3.0.4
django-ajax-selects==1.7.1
django-anymail==7.0.0
django-auth-ldap==2.2.0
django-countries==5.5
django-extensions==2.2.5
django-formtools==2.2
django-iprestrict==1.7.0
django-messages-ui==2.0.2
django-nose==1.4.6
django-otp==0.7.4
django-phonenumber-field==2.4.0
django-positions==0.6.0
django-rdrf==6.1.28
django-redis==4.11.0
django-registration-redux==2.6
django-reversion==3.0.5
django-session-security==2.6.5
django-simple-history==2.8.0
django-storages==1.8
django-templatetag-handlebars==1.3.1
django-templatetag-sugar==1.0
django-two-factor-auth==1.10.0
django-user-agents==0.3.2
django-useraudit==1.7.1
django-uwsgi==0.2.2
djangorestframework==3.9.4
et-xmlfile==1.0.1
geoip2==2.9.0
html5lib==1.1
idna==2.10
importlib-metadata==1.7.0
jdcal==1.4.1
jsonschema==3.2.0
kombu==4.6.8
maxminddb==2.0.2
nose==1.3.7
openpyxl==2.6.4
phonenumberslite==8.11.1
polib==1.1.0
psycopg2==2.8.4
pyasn1-modules==0.2.8
pyasn1==0.4.8
pycountry==19.8.18
pyinotify==0.9.6
pyodbc==4.0.27
pyparsing==2.4.5
pyrsistent==0.16.0
python-dateutil==2.8.1
python-ldap==3.3.1
python-memcached==1.59
pytz==2020.1
qrcode==6.1
redis==3.5.3
reportlab==3.5.48
requests==2.24.0
setuptools-scm==3.3.3
six==1.13.0
uWSGI==2.0.18
ua-parser==0.8.0
urllib3==1.25.10
user-agents==2.0
vine==1.3.0
webencodings==0.5.1
xhtml2pdf==0.2.4
zipp==3.1.0
